version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: vessel50_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=vessel50_development
      - POSTGRES_USER=marcelo
      - POSTGRES_PASSWORD=password123456789

  redis:
    image: 'redis:7.2.1-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/rails'
      - '/rails/tmp' # don't mount tmp directory
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
      - POSTGRES_HOST=db
      - POSTGRES_DB=vessel50_development
      - POSTGRES_USER=marcelo
      - POSTGRES_PASSWORD=password123456789

  web:
    depends_on:
      - db
      - redis
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_DB=vessel50_development
      - POSTGRES_USER=marcelo
      - POSTGRES_PASSWORD=password123456789
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

volumes:
  app-storage:
  redis:
