version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: vessel50_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=vessel50_development
      - POSTGRES_USER=marcelo
      - POSTGRES_PASSWORD=password123456789
    networks:
      - vessel-network

  redis:
    image: 'redis:7.2.1-alpine'
    command: redis-server
    volumes:
      - './web/redis:/data'
    networks:
      - vessel-network

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: './web'
    command: bundle exec sidekiq
    volumes:
      - './web:/rails'
      - '/rails/tmp'
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
      - POSTGRES_HOST=db
      - POSTGRES_DB=vessel50_development
      - POSTGRES_USER=marcelo
      - POSTGRES_PASSWORD=password123456789
    networks:
      - vessel-network

  web:
    depends_on:
      - db
      - redis
    build: ./web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - './web:/rails'
      - '/rails/tmp'
      - '/rails/db'
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_DB=vessel50_development
      - POSTGRES_USER=marcelo
      - POSTGRES_PASSWORD=password123456789
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    networks:
      - vessel-network

  web2:
    build: ./web2
    ports:
      - "8000:8000"
    volumes:
      - './web2:/django'
    networks:
      - vessel-network

volumes:
  app-storage:
  redis:

networks:
  vessel-network:
    driver: bridge
