default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  port: 54321
  username: marcelo
  password: password123456789

development:
  <<: *default
  database: vessel50_development

test:
  <<: *default
  database: vessel50_test

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
